Models/Category.cs
namespace CrudOperation.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public ICollection<Game> Games { get; set; } = new List<Game>();
    }
}

Models/Device.cs
namespace CrudOperation.Models
{
    public class Device
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Icon { get; set; } = string.Empty;

    }
}

Models/ErrorViewModel.cs
namespace CrudOperation.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Game.cs
namespace CrudOperation.Models;

public class Game
{
    public int Id { get; set; }
    public string Name { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string Cover { get; set; } = string.Empty;
    public int CategoryId { get; set; }
    public Category Category { get; set; } = default!;
    public ICollection<GameDevice> Devices { get; set; } = new List<GameDevice>();
}

Models/GameDevice.cs
namespace CrudOperation.Models
{
    public class GameDevice
    {
        public int GameId { get; set; }
        public Game game { get; set; } = default!;
        public int DeviceId { get; set; }
        public Device device { get; set; } = default!;


    }
}

ViewModels/CreateGameFormVM.cs
namespace CrudOperation.ViewModels;
public class CreateGameFormVM : GameFormVm
{

    [AllowedExtention(FileSet.AllowedExtensions), MaxSize(FileSet.MaxFileSizeInBytes)]
    public IFormFile Cover { get; set; } = default!;

}

ViewModels/EditeGameFormVm.cs
namespace CrudOperation.ViewModels;

public class EditeGameFormVm : GameFormVm
{
    public string? CurrantCover { get; set; }
    public int Id { get; set; }
    [AllowedExtention(FileSet.AllowedExtensions), MaxSize(FileSet.MaxFileSizeInBytes)]
    public IFormFile? Cover { get; set; } = default!;
}

ViewModels/GameFormVm.cs
namespace CrudOperation.ViewModels;

public class GameFormVm
{
    [MaxLength(250)]
    public string Name { get; set; } = string.Empty;
    [MaxLength(5000)]
    public string Description { get; set; } = string.Empty;
    [Display(Name = "Category")]
    public int CategoryId { get; set; }
    public IEnumerable<SelectListItem> Categories { get; set; } = Enumerable.Empty<SelectListItem>();
    [Display(Name = "Devices")]
    public List<int> SelectedDevices { get; set; } = default!;
    public IEnumerable<SelectListItem> Devices { get; set; } = Enumerable.Empty<SelectListItem>();
}

Controllers/GamesController.cs
using CrudOperation.Services;

namespace CrudOperation.Controllers
{
    public class GamesController : Controller
    {
        private readonly ICategoriesService _CategoriesService;
        public readonly IDevicesService _DevicesService;
        public readonly IGamesService _GamesService;

        public GamesController(ICategoriesService categoriesService, IDevicesService devicesService, IGamesService gamesService)
        {
            _CategoriesService = categoriesService;
            _DevicesService = devicesService;
            _GamesService = gamesService;
        }

        public IActionResult Index()
        {
            var detailedGame = _GamesService.GetAll();
            return View(detailedGame);
        }

        public IActionResult GetById(int id)
        {
            var Details = _GamesService.GetById(id);
            if (Details == null)
            {
                return NotFound();
            }
            return View(Details);
        }
        [HttpGet]
        public IActionResult Create()
        {
            CreateGameFormVM Createvm = new CreateGameFormVM()
            {
                Categories = _CategoriesService.GetCategories(),
                Devices = _DevicesService.GetDevices()
            };
            return View(Createvm);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateGameFormVM createModel)
        {
            if (!ModelState.IsValid)
            {
                createModel.Categories = _CategoriesService.GetCategories();
                createModel.Devices = _DevicesService.GetDevices();
                return View(createModel);
            }
            await _GamesService.CreateGame(createModel);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            var UpdatedGame = _GamesService.GetById(id);

            if (UpdatedGame is null)
                return NotFound();

            EditeGameFormVm EditVM = new()
            {
                Id = id,
                Name = UpdatedGame.Name,
                Description = UpdatedGame.Description,
                CategoryId = UpdatedGame.CategoryId,
                SelectedDevices = UpdatedGame.Devices.Select(d => d.DeviceId).ToList(),
                Categories = _CategoriesService.GetCategories(),
                Devices = _DevicesService.GetDevices(),
                CurrantCover = UpdatedGame.Cover
            };

            return View(EditVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(EditeGameFormVm UpdatedModel)
        {
            if (!ModelState.IsValid)
            {
                UpdatedModel.Categories = _CategoriesService.GetCategories();
                UpdatedModel.Devices = _DevicesService.GetDevices();
                return View(UpdatedModel);
            }

            try
            {
                var game = await _GamesService.Update(UpdatedModel);
            }
            catch (Exception ex)
            {
                return BadRequest(ex.Message);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var isDeleted = _GamesService.Delete(id);

            return isDeleted ? Ok() : BadRequest();
        }
    }
}

Controllers/HomeController.cs
using CrudOperation.Services;

namespace CrudOperation.Controllers
{
    public class HomeController : Controller
    {
        private readonly IGamesService _gamesService;

        public HomeController(IGamesService gamesService)
        {
            _gamesService = gamesService;
        }

        public IActionResult Index()
        {
            var detailedGame = _gamesService.GetAll();
            return View(detailedGame);
        }



        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Games/Create.cshtml
@model CreateGameFormVM
@{
    ViewData["Title"] = "Add Game";
}
<h4><i class="bi bi-emoji-grin"></i> Add New game</h4>
<form asp-controller="Games" asp-action="Create" enctype="multipart/form-data" >
<div class="row">
    <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Name" class="form-label mt-4"></label>
                <input type="text" class="form-control" asp-for="Name" placeholder="Enter Name" >
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="form-label mt-4"></label>
                <textarea asp-for="Description" class="form-control" placeholder="Description"></textarea>
                <span asp-validation-for="Description" class="text-danger" ></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="form-label mt-4"></label>
                <input type="file" class="form-control" asp-for="Cover"
                       data-rule-extension="@FileSet.AllowedExtensions.Replace(".", string.Empty)"
                       data-msg-extension="Not allowed extension" 
                       data-rule-SizeOfFile="@FileSet.MaxFileSizeInBytes"
                       data-msg-SizeOfFile="Maximum allowed size is @FileSet.MaxFileSizeInMB MB"/>
                <small class="form-text text-muted"> Only @FileSet.AllowedExtensions files are allowed with max size @(FileSet.MaxFileSizeInMB)Mb.</small>
                <span asp-validation-for="Cover" class="text-danger d-block"></span>
              
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="form-label mt-4"></label>
                <select class="form-select" asp-for="CategoryId" asp-items="Model.Categories"
                        data-placeholder="Select a category" data-minimum-results-for-search="Infinity">
                    <option value=""></option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SelectedDevices" class="form-label mt-4"></label>
                <select class="form-select" asp-for="SelectedDevices" asp-items="Model.Devices"
                        data-placeholder="Select a Device" data-minimum-results-for-search="Infinity">
                    <option></option>
                </select>
                <span asp-validation-for="SelectedDevices" class="text-danger"></span>
            </div>
           
            <button type="submit" class="btn btn-primary mt-4" >Submit</button>
    </div>
        <div class="col-md-6">
            <div class="col-md-6 d-flex justify-content-centerc pt-4">
                <img class="cover-preview d-none " alt="Cover" /> </div>
        </div>
</div>
</form>
@section Scripts{
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
    <script src="~/js/cover-preview.js" asp-append-version="true"></script>
}<script src="~/js/validator.js" asp-append-version="true"></script>

Views/Games/GetById.cshtml
@model Game

@{
    ViewData["Title"] = Model.Name;
}

<div class="card border-success rounded-4 mt-5 overflow-hidden">
    <div class="card-body p-0">
        <div class="row">
            <div class="col-md-8 px-5 py-4 d-flex flex-column justify-content-between">
                <div>
                    <h1 class="text-success fw-bolder">@Model.Name</h1>
                    <span class="badge bg-info fs-5 mb-4">@Model.Category?.Name</span>
                    <p class="fs-5">@Model.Description</p>
                </div>
                <div>
                    @foreach (var gameDevice in Model.Devices)
                    {
                        <i class="@gameDevice.device.Icon me-2 fs-1 text-secondary"></i>
                    }
                </div>
            </div>
            <div class="col-md-4">
                <img src="@($"{FileSet.ImagesPath}/{Model.Cover}")" alt="@Model.Name" class="w-100" />
            </div>
        </div>
    </div>
</div>

Views/Games/Index.cshtml
@model IEnumerable<Game>
@{
    ViewData["Title"] = "Games";
}
<a class="btn btn-info btn-lg mt-3" asp-action="Create"><i class="bi bi-plus-square"></i> Add Games</a>
@if (!Model.Any())
{
    <div class="alert  alert-warning mt-5">
        <h4 class="alert-heading">Warning No Games!</h4>
        <p class="mb-0">No games were added yet</p>
    </div>
}
else
{
<div class="mt-4">
        <table class="table table-hover">
            <tbody>
                @foreach(var ShowGame in Model)
                {
                    <tr class=" table-secondary">
                        <td><div class="d-flex">
                            <div class="pe-5">
                                    <img src="@($"{FileSet.ImagesPath}/{ShowGame.Cover}")" alt="@ShowGame.Name" style="max-width: 80px" />
                            </div>
                                <div class="d-flex flex-column justify-content-center">
                                    <h5 class="text-light">@ShowGame.Name</h5>
                                    <h7 class="text-info">@ShowGame.Category.Name</h7>
                        </div></div></td>
                        <td class="align-middle">
                            <div class="d-flex justify-content-end">
                                <a  class="btn btn-info rounded rounded-5 me-2" asp-controller="Games" asp-action="Update" asp-route-id="@ShowGame.Id">
                                    <i class="bi bi-pencil-square"></i>
                                </a>
                                <a href="javascript:;" class="btn btn-danger rounded rounded-5 js-delete" data-id="@ShowGame.Id">
                                    <i class="bi bi-trash3"></i>
                                </a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>


           
    </table>
</div>
}
@section Scripts {
    <script src="~/js/delete.js" asp-append-version="true"></script>
}

Views/Games/Update.cshtml
@model EditeGameFormVm

@{
    ViewData["Title"] = "Edit Game";
}

<h4><i class="bi bi-pen"></i> Edit game</h4>

<form asp-controller="Games" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-6">
            <div class="form-group">
                <label asp-for="Name" class="form-label mt-4"></label>
                <input type="text" class="form-control" asp-for="Name" placeholder="Name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="form-label mt-4"></label>
                <select class="form-select" asp-for="CategoryId" asp-items="Model.Categories"
                        data-placeholder="Select a category" data-minimum-results-for-search="Infinity">
                    <option value=""></option>
                </select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SelectedDevices" class="form-label mt-4"></label>
                <select class="form-select" asp-for="SelectedDevices" asp-items="Model.Devices"
                        data-placeholder="Select devices">
                    <option></option>
                </select>
                <span asp-validation-for="SelectedDevices" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="form-label mt-4"></label>
                <textarea asp-for="Description" class="form-control" placeholder="Description"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cover" class="form-label mt-4"></label>
                <input type="file" class="form-control" asp-for="Cover"
                       data-rule-extension="@FileSet.AllowedExtensions.Replace(".", string.Empty)"
                       data-msg-extension="Not allowed extension"
                       data-rule-filesize="@FileSet.MaxFileSizeInBytes"
                       data-msg-filesize="Maximum allowed size is @FileSet.MaxFileSizeInMB MB">
                <small class="form-text text-muted">Only @FileSet.AllowedExtensions files are allowed with max size @(FileSet.MaxFileSizeInMB)MB.</small>
                <span asp-validation-for="Cover" class="text-danger d-block"></span>
            </div>
            <button type="submit" class="btn btn-light text-black mt-4">Save</button>
        </div>
        <div class="col-md-6 d-flex justify-content-center pt-4 overflow-hidden">
            <img class="cover-preview" alt="Cover" src="@($"{FileSet.ImagesPath}/{Model.CurrantCover}")" />
        </div>
    </div>
</form>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script src="~/lib/jquery-validation/dist/additional-methods.min.js"></script>
<script src="~/js/validator.js" asp-append-version="true"></script>
    <script src="~/js/cover-preview.js" asp-append-version="true"></script>

}

Views/Home/Index.cshtml
@model IEnumerable<Game>

@{
    ViewData["Title"] = "Home Page";
}
@if (!Model.Any())
{
    <div class="alert  alert-warning mt-5">
        <h4 class="alert-heading">Warning No Games!</h4>
        <p class="mb-0">No games were added yet</p>
    </div>
}
else {



  <div class="row mt-5">
        @foreach (var game in Model)
        {
            <div class="col-lg-4 col-md-6">

                <a class="card border-success mb-3 text-decoration-none rounded-2 tstc" asp-controller="Games" asp-action="GetById" asp-route-id="@game.Id">
                    <div class="card-body" style="background-image : url(@($"{FileSet.ImagesPath}/{game.Cover}")); background-size:cover;background-position: center; height: 450px;">                  
                    </div>
                    <div class="card-footer text-muted d-flex justify-content-between align-items-center">
                        <div class="d-flex align-items-end h-100 ">
                            <span class="badge bg-primary fs-6">@game.Category?.Name</span>
                        </div>
                        <h5>@game.Name</h5>
                        <div>
                            @foreach (var gameDevice in game.Devices)
                            {
                                <i class="@gameDevice.device.Icon me-2 fs-4"></i>
                            }
                     </div>


               
                    </div>
             </a>
             </div>

        
        }
   </div>
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | CrudOperation</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nerko+One&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap-icons/font/bootstrap-icons.min.css" />
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link href="~/lib/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
    <link href="~/lib/select2/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CrudOperation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg bg-primary mb-3" data-bs-theme="dark" >
            <div class="container-fluid">
                <a class="navbar-brand"  asp-controller="Home" asp-action="Index">CrudOperation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between" >
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link active " asp-controller="Games" asp-action="Index">Games</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/select2/js/select2.min.js"></script>
    <script src="~/lib/sweetalert2/sweetalert2.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>